/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package evraktakip_v2;

import java.awt.Dimension;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Uğur Durmuş
 */
public class FrameRegister extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public FrameRegister() {
        initComponents();
        jLabel8.setVisible(false);
            jComboBox2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel7 = new javax.swing.JLabel();
        jtxtid = new javax.swing.JTextField();
        jtxtad = new javax.swing.JTextField();
        jPass1 = new javax.swing.JPasswordField();
        jPass2 = new javax.swing.JPasswordField();
        jtxtsoyad = new javax.swing.JTextField();
        jRadiohasta = new javax.swing.JRadioButton();
        jRadioDok = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<String>();
        jLabel8 = new javax.swing.JLabel();

        jLabel7.setText("Alan seçiniz:");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(400, 200));

        jtxtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtidActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadiohasta);
        jRadiohasta.setText("Hasta");
        jRadiohasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadiohastaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioDok);
        jRadioDok.setText("Doktor");
        jRadioDok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioDokActionPerformed(evt);
            }
        });

        jButton1.setText("Kaydol");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Id:");

        jLabel2.setText("Şifre:");

        jLabel3.setText("Şifre:");

        jLabel4.setText("İsim:");

        jLabel5.setText("Soyad:");

        jButton2.setText("Login Ekranına Dön");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("(En az 4 haneli, rakamlardan oluşmalı.)");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Diğer", "Kulak-Burun-Boğaz", "Dahiliye", "Ortapedi", "Cildiye", " " }));

        jLabel8.setText("Alan seçiniz:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtid)
                    .addComponent(jtxtad)
                    .addComponent(jPass1)
                    .addComponent(jPass2)
                    .addComponent(jtxtsoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadiohasta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioDok, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtsoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8))
                            .addComponent(jRadiohasta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioDok)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sifre = String.copyValueOf(jPass1.getPassword());
        String sifre2 = String.copyValueOf(jPass2.getPassword());
        String ad = jtxtad.getText();
        String soyad = jtxtsoyad.getText();
        String alan=jComboBox2.getSelectedItem().toString();
        int a = jtxtid.getText().length();

        boolean yokmu = true;
        boolean devammi = true;
        if (sifre.isEmpty() || sifre2.isEmpty() || ad.isEmpty() || soyad.isEmpty()) {
            devammi = false;
        }

        String iDesen = "[a-zA-Z]";
        Pattern p = Pattern.compile(iDesen);
        Matcher m = p.matcher(jtxtid.getText());
        if (devammi) {
            if (a < 4) {
                JOptionPane.showMessageDialog(this, "İd en az 4 haneli bir rakam olmalı", "Hata", JOptionPane.ERROR_MESSAGE);
            } else {

                if (m.find()) {
                    JOptionPane.showMessageDialog(this, "İd yalnızca sayıdan oluşmalıdır", "Hata", JOptionPane.ERROR_MESSAGE);
                } else {
                    int id = Integer.parseInt(jtxtid.getText());
                    if (sifre.equals(sifre2)) {
                        if (jRadioDok.isSelected()) {
                            for (Doktor doktor : Doktor.doktors) {
                                if (id == doktor.id) {
                                    yokmu = false;
                                    break;
                                }
                            }
                            if (yokmu) {
                                Doktor d = new Doktor(ad, soyad, sifre, id,alan);
                                JOptionPane.showMessageDialog(this, "başarılı");
                                reset();
                            } else {
                                JOptionPane.showMessageDialog(this, "bu id ye sahip bir doktor var");
                            }
                        } else if (jRadiohasta.isSelected()) {
                            for (Hasta h : Hasta.hastalar) {
                                if (id == h.id) {
                                    yokmu = false;
                                    break;
                                }
                            }
                            if (yokmu) {
                                Hasta d = new Hasta(ad, soyad, sifre, id);
                                JOptionPane.showMessageDialog(this, "başarılı");
                                reset();
                            } else {
                                JOptionPane.showMessageDialog(this, "bu id ye sahip bir hasta var");
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "Hasta veya Doktor seçeneklerini seçmelisiniz", "Hata", JOptionPane.ERROR_MESSAGE);

                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Şifre doğrulanamadı.", "Hata", JOptionPane.ERROR_MESSAGE);

                    }
                }
            }
//
        }
        else{
            JOptionPane.showMessageDialog(this, "Gerekli Alanları doldurunuz", "Hata", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        FrameLogin l = new FrameLogin();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioDokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioDokActionPerformed
        // TODO add your handling code here:
        if(jRadioDok.isSelected()){
            jLabel8.setVisible(true);
            jComboBox2.setVisible(true);
        }
        else if(jRadiohasta.isSelected()){
            jLabel8.setVisible(false);
            jComboBox2.setVisible(false);
        }
        
    }//GEN-LAST:event_jRadioDokActionPerformed

    private void jRadiohastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadiohastaActionPerformed
        // TODO add your handling code here:
        if(jRadiohasta.isSelected()){
            jLabel8.setVisible(false);
            jComboBox2.setVisible(false);
        }
    }//GEN-LAST:event_jRadiohastaActionPerformed

    private void jtxtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtidActionPerformed

    void reset() {
        jPass1.setText("");
        jPass2.setText("");
        jtxtad.setText("");
        jtxtsoyad.setText("");
        jtxtid.setText("");
        buttonGroup1.clearSelection();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPass1;
    private javax.swing.JPasswordField jPass2;
    private javax.swing.JRadioButton jRadioDok;
    private javax.swing.JRadioButton jRadiohasta;
    private javax.swing.JTextField jtxtad;
    private javax.swing.JTextField jtxtid;
    private javax.swing.JTextField jtxtsoyad;
    // End of variables declaration//GEN-END:variables
}
