/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package evraktakip_v2;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yavuz
 */
public class FrameDok extends javax.swing.JFrame {

    DefaultTableModel dtm = new DefaultTableModel();
    Doktor d1 = new Doktor();

    /**
     * Creates new form FrameDok
     */
//    public FrameDok() {
//        initComponents();
//        dtm.setRowCount(0);
//        jTable1.setModel(dtm);
//    }

    public FrameDok(Doktor d) {
        initComponents();
        jButton3.setEnabled(false);
        jLabel2.setVisible(false);
        jTextFieldSorgula.setVisible(false);
        jButtonGetir.setVisible(false);
        jLabel1.setText("Hoşgeldiniz doktor " + d.ad + " " + d.soyad);
        d1 = d;
       dtm.setColumnIdentifiers(new Object[]{"Radio Button seçiniz"});
//        dtm.addRow(new Object[]{"nosuz", "Boş", "Boş"});
          jTable1.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioGelenRapor = new javax.swing.JRadioButton();
        jRadioGidenRecete = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldSorgula = new javax.swing.JTextField();
        jButtonGetir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(400, 250));

        buttonGroup1.add(jRadioGelenRapor);
        jRadioGelenRapor.setText("Gelen Raporlar");
        jRadioGelenRapor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioGelenRaporActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioGidenRecete);
        jRadioGidenRecete.setText("Cevapladığım Raporlar");
        jRadioGidenRecete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioGidenReceteActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("jLabel1");

        jButton1.setText("Reçete Yaz");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Login Ekranına Dön");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Reçeteyi Düzenle");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Gönderdiğim Reçeteler");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("İsme Göre Sorgula:");

        jTextFieldSorgula.setDisabledTextColor(new java.awt.Color(0, 0, 204));

        jButtonGetir.setText("Getir");
        jButtonGetir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGetirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(289, 289, 289))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioGelenRapor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioGidenRecete))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton2))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldSorgula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonGetir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioGelenRapor)
                    .addComponent(jRadioGidenRecete)
                    .addComponent(jRadioButton1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldSorgula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonGetir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioGelenRaporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioGelenRaporActionPerformed
        // TODO add your handling code here:
        if (jRadioGelenRapor.isSelected()) {
            jButton1.setEnabled(true);
            jButton3.setEnabled(false);
            jLabel2.setVisible(false);
            jTextFieldSorgula.setVisible(false);
            jButtonGetir.setVisible(false);
        }
        dtm.setColumnIdentifiers(new Object[]{"Rapor No", "Gönderen Hasta", "Başlık"});
        dtm.setRowCount(0);
        for (Rapor rapor : d1.gelenRaporlar) {
            dtm.addRow(new Object[]{
                rapor.raporId,
                rapor.GonderenHasta.ad + " " + rapor.GonderenHasta.soyad,
                rapor.baslik
            });
        }
        jTable1.setModel(dtm);
    }//GEN-LAST:event_jRadioGelenRaporActionPerformed

    private void jRadioGidenReceteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioGidenReceteActionPerformed
        // TODO add your handling code here:
        if (jRadioGidenRecete.isSelected()) {
            jButton1.setEnabled(false);
            jButton3.setEnabled(false);
            jLabel2.setVisible(false);
            jTextFieldSorgula.setVisible(false);
            jButtonGetir.setVisible(false);

        }
        dtm.setRowCount(0);
        for (Rapor rapor : d1.cevapladigimRaporlar) {
            dtm.addRow(new Object[]{rapor.raporId,rapor.GonderenHasta.ad+""+rapor.GonderenHasta.soyad,rapor.baslik});
            jTable1.setModel(dtm);
        }
    }//GEN-LAST:event_jRadioGidenReceteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        boolean secilimi = false;
        Rapor r ;
        Hasta gondrenH=null;
        if (jTable1.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Lütfen rapor seçiniz.", "Hata", JOptionPane.ERROR_MESSAGE);
        } else {
            secilimi = true;
        }

        if (secilimi) {
            String value = jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0).toString();
            for (Rapor rapor : d1.gelenRaporlar) {
                if (rapor.raporId == Integer.parseInt(value)) {
                    gondrenH=rapor.GonderenHasta;
                    r = rapor;
                    
                    FrameSendRecete frmrecete = new FrameSendRecete(r, d1, gondrenH);
                    frmrecete.setVisible(true);
                    buttonGroup1.clearSelection();
                    dtm.setRowCount(0);
                    break;
                }

            }
            
            

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        FrameLogin login=new FrameLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(jTable1.getSelectedRow()!=-1){
        
        
        Recete r=null;
        Hasta hh=null;
        int seciliId=(int)jTable1.getValueAt(jTable1.getSelectedRow(), 0);
        for (Recete rapor : d1.gonderdiğimReceteler) {
            if(seciliId==rapor.receteId){
               hh=rapor.gidenHasta; 
            r=rapor;
            d1.gonderdiğimReceteler.remove(r);
            hh.gelenRecete.remove(r);
            break;
            }
            
        }
        FrameReceteEdit rct=new FrameReceteEdit(r,d1,hh);
        rct.setVisible(true);
        
        }
        else{
        JOptionPane.showMessageDialog(this, "Lüften bir seçim yapınız!", "Hata", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton1.isSelected()) {
            jButton1.setEnabled(false);
            jButton3.setEnabled(true);
            jLabel2.setVisible(true);
            jTextFieldSorgula.setVisible(true);
            jButtonGetir.setVisible(true);
        }
        dtm.setColumnIdentifiers(new Object[]{"Id","Hasta İsmi","Başlık"});
        dtm.setRowCount(0);
        for (Recete recete : d1.gonderdiğimReceteler) {
            dtm.addRow(new Object[]{
                recete.receteId,
                recete.gidenHasta.ad + " " + recete.gidenHasta.soyad,
                recete.baslik
                
            });
        }
        jTable1.setModel(dtm);
        

    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButtonGetirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGetirActionPerformed
        // TODO add your handling code here:
        dtm.setRowCount(0);
        dtm.setColumnIdentifiers(new Object[]{"Hasta İsmi","Id","Başlık"});
        if(jTextFieldSorgula.getText().isEmpty() || jTextFieldSorgula.getText()==null){
            return;
        }
        
        for (Recete recete : d1.gonderdiğimReceteler) {
            if(recete.gidenHasta.ad.toLowerCase().startsWith(jTextFieldSorgula.getText())){
                dtm.addRow(new Object[]{
                    recete.gidenHasta.ad +recete.gidenHasta.soyad,
                    recete.baslik,
                    recete.receteId
                
                });
            }
        }
    }//GEN-LAST:event_jButtonGetirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameDok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameDok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameDok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameDok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrameDok().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonGetir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioGelenRapor;
    private javax.swing.JRadioButton jRadioGidenRecete;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldSorgula;
    // End of variables declaration//GEN-END:variables
}
